# Generated by Django 4.1.7 on 2023-03-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='2021-02-22'),
            preserve_default=False,
        ),
    ]
